import { useState, useEffect } from 'react'
import { ref, onValue, set, push } from 'firebase/database'
import { database } from '../../firebase/config'
import { useNavigate } from 'react-router-dom'
import './Dashboard.css'

import { SECOND_MD_CONFIG } from '../../utils/constants'

function MDDashboard() {
    const navigate = useNavigate()
    const [viewMode, setViewMode] = useState('cards') // 'cards' or 'grid'
    const [loading, setLoading] = useState(true)
    const [stats, setStats] = useState({
        totalEmployees: 0,
        presentToday: 0,
        onLeave: 0,
        onSite: 0
    })
    const [employees, setEmployees] = useState([])
    const [attendanceData, setAttendanceData] = useState([])
    const [selectedMonth, setSelectedMonth] = useState(new Date().toISOString().slice(0, 7))

    useEffect(() => {
        const attendanceRef = ref(database, 'attendance')
        const unsubscribe = onValue(attendanceRef, (snapshot) => {
            const data = snapshot.val()
            if (data) {
                const records = Object.values(data)
                setAttendanceData(records)

                // Process Stats for Today
                const today = new Date().toISOString().split('T')[0]
                const todayRecords = records.filter(r => r.date === today)

                // Get Unique Employees
                const empMap = new Map()
                records.forEach(r => {
                    if (!empMap.has(r.employeeEmail)) {
                        empMap.set(r.employeeEmail, {
                            email: r.employeeEmail,
                            name: r.employeeName,
                            lastSeen: r.date
                        })
                    } else {
                        // Update last seen
                        const existing = empMap.get(r.employeeEmail)
                        if (new Date(r.date) > new Date(existing.lastSeen)) {
                            existing.lastSeen = r.date
                        }
                    }
                })
                const empList = Array.from(empMap.values())
                setEmployees(empList)

                // Calculate Stats
                const present = todayRecords.filter(r => r.status === 'approved').length
                const site = todayRecords.filter(r => r.status === 'approved' && r.location === 'site').length
                // Leaves logic would go here if we had explicit leave records

                setStats({
                    totalEmployees: empList.length,
                    presentToday: present,
                    onLeave: 0, // Placeholder
                    onSite: site
                })

                // --- 2nd MD Auto-Attendance Logic ---
                handleSecondMDAttendance(records, today)
            }
            setLoading(false)
        })
        return () => unsubscribe()
    }, [])

    const handleSecondMDAttendance = async (records, todayStr) => {
        // Check last 7 days to backfill if missed
        const daysToCheck = 7
        const today = new Date()

        for (let i = 0; i < daysToCheck; i++) {
            const d = new Date()
            d.setDate(today.getDate() - i)

            // Skip Sundays
            if (d.getDay() === 0) continue

            const dateStr = d.toISOString().split('T')[0]

            // Check if 2nd MD has attendance for this date
            const hasAttendance = records.some(r =>
                r.employeeEmail === SECOND_MD_CONFIG.email &&
                r.date === dateStr
            )

            if (!hasAttendance) {
                console.log(`Auto-marking attendance for 2nd MD on ${dateStr}...`)
                try {
                    const newRef = push(ref(database, 'attendance'))
                    await set(newRef, {
                        employeeEmail: SECOND_MD_CONFIG.email,
                        employeeName: SECOND_MD_CONFIG.name,
                        date: dateStr,
                        timestamp: d.getTime(), // Use noon for timestamp to be safe? Or just current time if today
                        location: 'office',
                        status: 'approved',
                        siteName: '',
                        autoGenerated: true
                    })
                } catch (error) {
                    console.error(`Failed to auto-mark 2nd MD attendance for ${dateStr}:`, error)
                }
            }
        }
    }

    const getDaysInMonth = (monthStr) => {
        const [year, month] = monthStr.split('-')
        const date = new Date(year, month, 0)
        const days = date.getDate()
        const daysArray = []
        for (let i = 1; i <= days; i++) {
            daysArray.push(new Date(year, month - 1, i))
        }
        return daysArray
    }

    const days = getDaysInMonth(selectedMonth)

    const getAttendanceStatus = (empEmail, date) => {
        const dateStr = date.toISOString().split('T')[0]
        const record = attendanceData.find(r => r.employeeEmail === empEmail && r.date === dateStr)

        if (!record) return null
        return record
    }

    return (
        <div className="md-page-container">
            <div className="md-content-wrapper">
                <header className="page-header">
                    <div>
                        <h1>Dashboard</h1>
                        <p>Overview of attendance and employee status</p>
                    </div>
                    <div className="header-controls">
                        <div className="view-toggle">
                            <button
                                className={`toggle-btn ${viewMode === 'cards' ? 'active' : ''}`}
                                onClick={() => setViewMode('cards')}
                            >
                                Cards
                            </button>
                            <button
                                className={`toggle-btn ${viewMode === 'grid' ? 'active' : ''}`}
                                onClick={() => setViewMode('grid')}
                            >
                                Grid
                            </button>
                        </div>
                        {viewMode === 'grid' && (
                            <input
                                type="month"
                                value={selectedMonth}

                                onChange={(e) => setSelectedMonth(e.target.value)}
                                className="month-selector"
                            />
                        )}
                    </div>
                </header>

                {/* Summary Stats */}
                <div className="stats-grid">
                    <div className="stat-card">
                        <div className="stat-icon total">👥</div>
                        <div className="stat-info">
                            <h3>Total Employees</h3>
                            <p>{stats.totalEmployees}</p>
                        </div>
                    </div>
                    <div className="stat-card">
                        <div className="stat-icon present">✅</div>
                        <div className="stat-info">
                            <h3>Present Today</h3>
                            <p>{stats.presentToday}</p>
                        </div>
                    </div>
                    <div className="stat-card">
                        <div className="stat-icon site">🏗️</div>
                        <div className="stat-info">
                            <h3>On Site</h3>
                            <p>{stats.onSite}</p>
                        </div>
                    </div>
                    <div className="stat-card">
                        <div className="stat-icon leave">🏖️</div>
                        <div className="stat-info">
                            <h3>On Leave</h3>
                            <p>{stats.onLeave}</p>
                        </div>
                    </div>
                </div>

                {/* Main Content */}
                {loading ? (
                    <div className="loading-state">Loading data...</div>
                ) : viewMode === 'cards' ? (
                    <div className="employee-cards-grid">
                        {employees.map(emp => (
                            <div key={emp.email} className="emp-summary-card">
                                <div className="emp-card-header">
                                    <div className="emp-avatar">
                                        {(emp.name || emp.email || 'U').charAt(0).toUpperCase()}
                                    </div>
                                    <div className="emp-details">
                                        <h4>{emp.name || emp.email || 'Unknown'}</h4>
                                        <span className="last-seen">Last seen: {emp.lastSeen}</span>
                                    </div>
                                </div>
                                <button
                                    className="view-profile-btn"
                                    onClick={() => navigate(`/md/profiles/${encodeURIComponent(emp.email)}`)}
                                >
                                    View Profile
                                </button>
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="calendar-grid-container">
                        <table className="calendar-table">
                            <thead>
                                <tr>
                                    <th className="sticky-col">Employee</th>
                                    {days.map(day => (
                                        <th key={day.toISOString()} className={day.getDay() === 0 ? 'sunday-header' : ''}>
                                            {day.getDate()}
                                        </th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody>
                                {employees.map(emp => (
                                    <tr key={emp.email}>
                                        <td className="sticky-col name-col">{emp.name}</td>
                                        {days.map(day => {
                                            const status = getAttendanceStatus(emp.email, day)
                                            const isSunday = day.getDay() === 0
                                            let cellClass = isSunday ? 'sunday-cell' : 'empty-cell'
                                            let content = ''

                                            if (status) {
                                                if (status.status === 'approved') {
                                                    cellClass = status.location === 'office' ? 'present-office' : 'present-site'
                                                    content = status.location === 'office' ? 'O' : 'S'
                                                } else if (status.status === 'pending') {
                                                    cellClass = 'pending-cell'
                                                    content = 'P'
                                                }
                                            }

                                            return (
                                                <td key={day.toISOString()} className={`grid-cell ${cellClass}`}>
                                                    {content}
                                                </td>
                                            )
                                        })}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    )
}

export default MDDashboard
